package:
  name: potrace
  version: 1.15
build:
  number: 0
  #skip: True # [osx]
source:
  fn: potrace-1.15.linux-x86_64.tar.gz
  url: https://downloads.sourceforge.net/project/potrace/1.15/potrace-1.15.tar.gz?r=https%3A%2F%2Fsourceforge.net%2Fprojects%2Fpotrace%2Ffiles%2F1.15%2Fpotrace-1.15.tar.gz%2Fdownload%3Fuse_mirror%3Dayera&ts=1528389557
requirements:
  build:
    - gcc   [linux]
  run:
test:
  commands:
    - "potrace --help"
about:
  home: http://potrace.sourceforge.net
  license: GPL
  summary: A tool for tracing a bitmap, which means, transforming a bitmap into a smooth, scalable image
